import { existsSync, mkdirSync, writeFileSync, chmodSync } from 'node:fs';
import { join } from 'node:path';

export function installGitHook(repoPath: string): void {
  const hooksDir = join(repoPath, '.git', 'hooks');
  const hookPath = join(hooksDir, 'commit-msg');

  if (!existsSync(join(repoPath, '.git'))) {
    throw new Error('Not a git repository. Run this command from the root of a git repository.');
  }

  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  const hookContent = `#!/bin/sh
# commit-lint-gen hook
# Auto-generated by clg init
# Validates commit messages against conventional commits format

COMMIT_MSG_FILE=$1

# Run linter on the commit message
clg lint "$(cat "$COMMIT_MSG_FILE")"

# Exit with linter's exit code
exit $?
`;

  writeFileSync(hookPath, hookContent, { mode: 0o755 });

  try {
    chmodSync(hookPath, 0o755);
  } catch (error) {
    // chmod might fail on Windows, but that's okay
  }

  console.log('✓ Git hook installed successfully!');
  console.log(`  Location: ${hookPath}`);
  console.log('\nThe hook will validate commit messages automatically.');
  console.log('To generate commit messages, run: clg generate');
}

export function uninstallGitHook(repoPath: string): void {
  const hookPath = join(repoPath, '.git', 'hooks', 'commit-msg');

  if (!existsSync(hookPath)) {
    console.log('No git hook found to uninstall.');
    return;
  }

  const fs = require('node:fs');
  const content = fs.readFileSync(hookPath, 'utf-8');

  if (!content.includes('commit-lint-gen hook')) {
    throw new Error('The commit-msg hook was not installed by clg. Please remove it manually if needed.');
  }

  fs.unlinkSync(hookPath);
  console.log('✓ Git hook uninstalled successfully!');
}
